export const properties = [
  {
    id: 1,
    img: "/assets/properties/1.png",
    title: "Brooklyn Park",
    price: "$221,095",
    type: "Townhouse",
    beds: "3",
    sqft: "2,150",
    bathrooms: "2",
    cuttedPrice: "250,000",
    is_discounted: true,
  },
  {
    id: 2,
    img: "/assets/properties/2.png",
    title: "Brooklyn Park",
    price: "$221,095",
    type: "Townhouse",
    beds: "3",
    sqft: "2,150",
    bathrooms: "2",
    cuttedPrice: "250,000",
    is_discounted: true,
  },
  {
    id: 3,
    img: "/assets/properties/3.png",
    title: "Brooklyn Park",
    price: "$221,095",
    type: "Townhouse",
    beds: "3",
    sqft: "2,150",
    bathrooms: "2",
  },
  {
    id: 4,
    img: "/assets/properties/3.png",
    title: "Brooklyn Park",
    price: "$221,095",
    type: "Townhouse",
    beds: "3",
    sqft: "2,150",
    bathrooms: "2",
  },
];
